version: '3.7'

services:
  productpage:
    build:
      context: ./productpage
      dockerfile: Dockerfile
    environment:
      - GROUP_NUMBER=24
    ports:
      - "9080:9080"
    volumes:
      - vol-productpage:/home/upm/Desktop/pc2n/p3/volumes/productpage

  details:
    build:
      context: ./details
      dockerfile: Dockerfile
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    volumes:
      - vol-details:/home/upm/Desktop/pc2n/p3/volumes/details
    ports:
      - "9080"

  reviews:
    build:
      context: ./reviews
      dockerfile: Dockerfile
    environment:
      - ENABLE_RATINGS=true #en v1 es false
      - SERVICE_VERSION=v3 #v1, v2
      - STAR_COLOR=red #v2 es black y en v1 no hay estrella
    volumes:
      - vol-reviews:/home/upm/Desktop/pc2n/p3/volumes/reviews
    ports:
      - "9080"

  ratings:
    build:
      context: ./ratings
      dockerfile: Dockerfile
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE=true
    volumes:
      - vol-ratings:/home/upm/Desktop/pc2n/p3/volumes/ratings
    ports:
      - "9080"

volumes:
  vol-productpage:
  vol-details:
  vol-reviews:
  vol-ratings:
