services:
  productpage:
    build:
      context: ./productpage
    image: productpage/24
    container_name: productpage-24
    ports:
      - "9080:9080"
    environment:
      GROUP_NUMBER: "24"
    depends_on:
      - details
      - ratings
      - reviews

  details:
    build:
      context: ./details
    image: details/24
    container_name: details-24
    ports:
      - "9081:9080"
    environment:
      SERVICE_VERSION: v1
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"

  reviews:
    image: reviews/24:v3  # Cambia segun la version
    container_name: reviews-24
    ports:
      - "9082:9080"
    environment:
      ENABLE_RATINGS: "true" #para v1 es false
      SERVICE_VERSION: v3  # Cambia según la versión
      STAR_COLOR: "red" #cambia segun la version, para el resto black
  
  ratings:
    build:
      context: ./ratings
    image: ratings/24
    container_name: ratings-24
    ports:
      - "9083:9080"
    environment:
      SERVICE_VERSION: v1
