version: '3.7'

services:
  productpage: 
    build:
      context: ./productpage
    environment:
      - GROUP_NUMBER=24
    image: productpage/24 #las imagenes son microserv/numgroup
    container_name: productpage-24 #nombreservicio-24
    ports:
      - "9080:9080"
    volumes:
      - vol-productpage:/home/upm/Desktop/pc2n/p3/volumes/productpage

  details:
    build:
      context: ./details
    environment:
      - SERVICE_VERSION=v1
      - ENABLE_EXTERNAL_BOOK_SERVICE= "true"
    image: details/24 
    container_name: details-24
    volumes:
      - vol-details:/home/upm/Desktop/pc2n/p3/volumes/details
    ports:
      - "9080"

  reviews:
    build:
      context: practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg
    image: reviews/24 
    container_name: reviews-24
    volumes:
      - vol-reviews:/home/upm/Desktop/pc2n/p3/volumes/reviews
    ports:
      - "9080"

  ratings:
    build:
      context: ./ratings
    environment:
      - SERVICE_VERSION=v1
    image: ratings/24 
    container_name: ratings-24
    volumes:
      - vol-ratings:/home/upm/Desktop/pc2n/p3/volumes/ratings
    ports:
      - "9080"

volumes:
  vol-productpage:
  vol-details:
  vol-reviews:
  vol-ratings: